# Các nền tảng tài trợ cho dự án
# Bỏ comment và điền thông tin của bạn

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# custom: ['https://example.com/donate']
